# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0008_auto_20151215_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tim',
            name='spirit',
            field=models.BooleanField(default=True),
        ),
    ]
