# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrac', '0017_auto_20160106_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrac',
            name='miesto_bydliska',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='telefonne_cislo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
