# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrac', '0018_auto_20160111_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrac',
            name='datum_narodenia',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='krstne_meno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='pohlavie',
            field=models.CharField(blank=True, choices=[('Mu\u017e', 'Mu\u017e'), ('\u017dena', '\u017dena')], default=b'Mu\xc5\xbe', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='priezvisko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
