# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategoriaTurnaju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriaturnaju',
            name='pocet_timov',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
