# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0008_remove_turnaj_spirit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnaj',
            name='datum_do',
            field=models.DateField(default=datetime.date(2016, 1, 24)),
        ),
        migrations.AlterField(
            model_name='turnaj',
            name='datum_od',
            field=models.DateField(default=datetime.date(2016, 1, 23)),
        ),
    ]
