# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0009_auto_20160127_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnaj',
            name='datum_do',
            field=models.DateField(blank=True, default=datetime.date(2016, 2, 7), null=True),
        ),
        migrations.AlterField(
            model_name='turnaj',
            name='datum_od',
            field=models.DateField(blank=True, default=datetime.date(2016, 2, 6), null=True),
        ),
        migrations.AlterField(
            model_name='turnaj',
            name='datum_zapisu',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='turnaj',
            name='mesto',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turnaj',
            name='stat',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
    ]
