# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 23:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krstne_meno', models.CharField(blank=True, max_length=50, null=True)),
                ('priezvisko', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonne_cislo', models.CharField(blank=True, max_length=50, null=True)),
                ('pohlavie', models.CharField(blank=True, choices=[('Mu\u017e', 'Mu\u017e'), ('\u017dena', '\u017dena')], default=b'Mu\xc5\xbe', max_length=5, null=True)),
                ('datum_narodenia', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('miesto_bydliska', models.CharField(blank=True, max_length=255, null=True)),
                ('prezivka', models.CharField(max_length=50)),
                ('foto', models.CharField(blank=True, default=b'', max_length=250, null=True)),
                ('poznamka', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hraci',
            },
        ),
        migrations.CreateModel(
            name='HracTimu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.Hrac')),
            ],
            options={
                'verbose_name_plural': 'Hraci Timov',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='KategoriaTurnaju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_timov', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.Kategoria')),
            ],
            options={
                'verbose_name_plural': 'Kategorie Turnajov',
            },
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kluby',
            },
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umiestnenie', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('nazov', models.CharField(default=b'', max_length=50)),
                ('spirit', models.BooleanField(default=True)),
                ('kategoria_turnaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.KategoriaTurnaju')),
                ('klub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee.Klub')),
            ],
            options={
                'verbose_name_plural': 'Timy',
            },
        ),
        migrations.CreateModel(
            name='Turnaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=50)),
                ('datum_od', models.DateField(blank=True, default=datetime.date(2016, 2, 6), null=True)),
                ('datum_do', models.DateField(blank=True, default=datetime.date(2016, 2, 7), null=True)),
                ('mesto', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('stat', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('datum_zapisu', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('report', models.CharField(blank=True, default=b'', max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Turnaje',
            },
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vysledok_1', models.IntegerField()),
                ('vysledok_2', models.IntegerField()),
                ('kategoria_turnaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.KategoriaTurnaju')),
                ('tim_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tim', to='frisbee.Tim')),
                ('tim_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='zapas_tim', to='frisbee.Tim')),
            ],
            options={
                'verbose_name_plural': 'Zapasy',
            },
        ),
        migrations.AddField(
            model_name='kategoriaturnaju',
            name='turnaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.Turnaj'),
        ),
        migrations.AddField(
            model_name='hractimu',
            name='tim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbee.Tim'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='klub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbee.Klub'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
